### ISSUE TITLE
Engelsk tekst i modal 

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#108]
![2020-03-18_13-15-06](https://user-images.githubusercontent.com/11901064/76961053-f1813900-691c-11ea-9f67-4288a8c09304.png)
Dette burde være norsk

**Comment by plusk** [comment]
Vi kommer tilbake til denne når vi ser på å integrere det inn i logg-inn flyten fremfor å bruke en modal dialog vi ikke har så mye kontroll på selv
