### ISSUE TITLE
Forbedringer innen UU

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#109]
**Hva ønsker du deg**
Vi har ikke fokusert på UU under utvilking. Det er på tide å ta en pass for å fikse opp i dette. Vi kan sjekke ut ARC Toolkit.

**Comment by plusk** [comment]
Jeg tok en liten runde på dette etter input fra Nav, skal være mulig å navigere gjennom ting med tastaturet nå med #118 Kan åpne nytt issue når vi har nye konkrete ting å ta tak i
