### ISSUE TITLE
Karantenehjelpen fortsetter å bruke posisjonen etter lukking av siden.

### ISSUE THREAD

**Issue by johanneskvamme** [s0lvang/Karantenehjelpen#111]
**Beskriv hva som skjer **

Obskur bug, men karantenehjelpen "frigir" ikke posisjonsforespørselen. Litt usikker på om det er noe som lagres i session eller noe som gjør det, men etter å ha "åpnet Karantenehjelpen i en ny fane, godtatt posisjonsdeling, lukket Karantenehjelpen-fanen", så melder Windows at Firefox fortsatt bruker min posisjon.

Ikonet kom etter åpning av Karantenehjelpen og godkjenning av at den kunne bruke GPS.
Den er der fremdeles etter lukking av fanen.
![](https://folk.ntnu.no/johannkv/img/OQOQHIi0tW.png)

**Annet**

Firefox 74, Windows.

**Comment by FredrikAugust** [comment]
Det er en timeout på 3 sekunder på position-requestet, men APIene for lokasjon i browsere er veldig buggy, så er mulig den bare henger igjen og loker.

**Comment by FredrikAugust** [comment]
Tror bare denne må flyttes til wontfix og lukkes, for den spør bare om én posisjon, og det her er nok browserens implementasjon som loker.

**Comment by johanneskvamme** [comment]
Enig i at det ikke er noe krise, og at det ikke haster, men at det er browseren sin feilimplementasjon tror jeg er feil. Testet på én-to (Power.no blant annet) ulike nettbutikker hvor "Finn butikk" spør om posisjon, "posisjon i bruk"-ikonet dukker opp, fanen lukkes og "posisjon i bruk"-ikonet forsvinner.

**Comment by FredrikAugust** [comment]
Har satt en timeout på 5 (my bad) sekunder som kun kjøres når Vuex-store settes opp, så burde ikke kunne brukes etter det. Grunnen til at jeg mistenker at det er Browser sin feil er fordi det ser litt ut som om den holder på requestet etter at du lukker siden, fram til den timer ut eller går gjennom.

Har dog hatt problemer med at browsere ikke hører på argumentene til `getCurrentPosition`.
