### ISSUE TITLE
Funker ikke i FB browser

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#123]
**Hva ønsker du deg**
Dette er full krise, siden vi spres så mye på FB. 

Vi tror det er google login som ikke funker

**Comment by johanneskvamme** [comment]
Funker ikke i Android sin minimale browser heller (den man bruker om man trykker på lenker/går via Google-søk Widget). Kommer til callback fra Google (karantenhjelpen.firebase...) også forblir den der.

**Comment by aslakhol** [comment]
Sånn det står nå så virker som om ikke funker i messenger browser på iphone. Men fungerer på iphone. Kan du sjekke ditt testcase @FluidSense ?

**Comment by johanneskvamme** [comment]
Hva skal jeg sjekke? Nyeste versjon? @aslakhol

**Comment by Adrianht** [comment]
Prod fungerer nå for meg på iPhone via Facebook.com, men ikke via messenger. Virker som begge fungerer på Android tho @FluidSense

**Comment by johanneskvamme** [comment]
Yes, fungerer i Android's minimale browser nå ja! 👏 👏

**Comment by Adrianht** [comment]
Ettersom det er fikset for de fleste lukkes denne. Lager et nytt issue for iPhone-messenger #170
