### ISSUE TITLE
Reduserer synlighet av privatinfo

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#141]
**Hva ønsker du deg**
Akkurat nå så viser tlf og epost til alle bestillingene med en gang. Det er nok litt uheldig da disse gjør folk veldig lett å identifisere. 

Vi blir nødt til å vise adressen, men jeg foreslår at vi skjuler tlf og epost frem til du har tatt oppdraget. 

Bittelitt conditional rendering altså.

**Comment by FredrikAugust** [comment]
Jeg kan ta det her etterpå hvis det passer?

**Comment by aslakhol** [comment]
Kjør på, jeg ga det ganske høy prioritering og burde være pretty ez.
