### ISSUE TITLE
Placeholdernummeret vårt ser ikke ut som et placeholdernummer

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#161]
**Hva ønsker du deg**
![image](https://user-images.githubusercontent.com/11901064/77111982-86248d80-6a28-11ea-8b69-ac95adb2a864.png)
Slik ser det ut om man ikke har et telefonnummer per nå. Det bør komme tydelig frem at dette er et placeholdernummer. Kanskje man bare skal bruke 0000000?

**Comment by aweibell** [comment]
Viss ein treng placeholder? 00000000 er definitivt betre enn 98765432! :)

https://www.180.no/search/all?w=98765432

**Comment by FredrikAugust** [comment]
Stakkars type, lurer på hvor mange tulle-sms-er han har fått
