### ISSUE TITLE
[Login] word break i informasjon om tjenesten

### ISSUE THREAD

**Issue by thomand** [s0lvang/Karantenehjelpen#163]
Det er litt uheldig bryting av teksten om tjenesten på login-siden.

Har sjekket koden og det er ikke tilfelle, men det kan se ut som oppførselen på p-tagene er som om man hadde hatt

```
p {
    word-break: break-all;
}
```

Mulig dere kan teste med å endre til

```
p {
    word-break: normal;
}
```

Skulle laget PR etter å ha testet litt, men får ikke kjørt opp koden uten .env

Ellers: veldig bra insj! 👏 

<img width="827" alt="Skjermbilde 2020-03-19 kl  21 51 33" src="https://user-images.githubusercontent.com/6693662/77114126-49f32c00-6a2c-11ea-9d0c-58453492b414.png">

**Comment by FredrikAugust** [comment]
Takk for issue! Skal ta en titt nå :)

**Comment by kharann** [comment]
Vi skal jobbe med å få en mer detaljert readme, ref #59 , så det blir lettere å bidra!
