### ISSUE TITLE
Sorter oppdragslisten basert på avstand

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#30]
**Hva ønsker du deg**
Det hadde vært smud om listen var sortert basert på hvilke oppdrag var nærmest deg.

**Comment by FredrikAugust** [comment]
Dette hadde vært en kul feature, men gjør at vi må hente ut geoposisjon fra brukerens laptop/mobil. Dette er en ganske buggy prosess, og spesielt chrome elsker å bare ikke gi deg noe tilbake i tid og utide, så hvis noen skal begi seg ut på dette, ikke nøl med å sende meg en melding, har en del erfaring fra nettopp dette.
