### ISSUE TITLE
Vis tlf til den som har tatt et oppdrag

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#36]
**Hva ønsker du deg**
Vi må vise tlf til den som tar oppdraget.

**Comment by FredrikAugust** [comment]
Så på det her i stad, men man får ikke det ut fra auth-systemet vi bruker nå, så da må det eventuelt legges på et ekstra registreringssteg.

**Comment by s0lvang** [comment]
Yeah! Er sikkert litt herk å få det til, men tror ikke det skal være alt for vanskelig. Vet ikke helt hvor høyt vi skal prioritere det, for det fungerer egentlig fint at den personen som tar oppdraget bare ringer. De som tar runder og gjør ting er jo mest sannsynlig utadvendte folk som vl hjelpe

**Comment by s0lvang** [comment]
nvm jeg tar det

**Comment by s0lvang** [comment]
Venter med den til imorgen :P Så hvis noen føler seg inspirert er det bare å kjøre på
