### ISSUE TITLE
Se totaloverskt av bestillinger på kart

### ISSUE THREAD

**Issue by plusk** [s0lvang/Karantenehjelpen#46]
**Hva ønsker du deg**
Litt sånn som når man ser på boliger på Finn, så er det kjekt å se en kartvisning med alle adressene på. Kanskje man kan trykke på de pin'ene og ta oppdrag så man kan lett plotte en rute selv

**Comment by michaelmcmillan** [comment]
Kult prosjekt! Denne vil jeg +1

Enklere å forholde seg til enn å måtte lese adressene i listen :)
