### ISSUE TITLE
Mer margin på bunn når man har tatt et oppdrag. 

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#49]
**Beskriv hva som skjer **
Når du har tatt et oppdrag kommer det en tekst som forklarer hva dette betyr. På min telefon blir hjørnene av denne teksten kuttet av kurvingen på mobilskjermen. Vi bør gi den litt mer rom. 

**Annet**
OP6

**Comment by FredrikAugust** [comment]
On it, sir.
