### ISSUE TITLE
Marker hvilke oppdrag du har tatt i oppdragslisten

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#55]
**Hva ønsker du deg**
Den relevante flyten er: 
Oppdragslisten -> inn på et oppdrag -> ta oppdraget -> tilbake til oppdragslisten

Vi ville at oppdraget fortsatt skulle være i listen, så det ikke plutselig forsvant bare fordi du hadde tatt det. Men det gjør at det er vanskelig å se at du faktisk har tatt et oppdrag. 

Vi ønsker derfor en slags markering av at du har tatt oppdraget. Kanskje en farget bånd på skrå over et hjørne av oppdraget?

**Comment by s0lvang** [comment]
solved by #71
