### ISSUE TITLE
Tekstmelding om at noen har tatt oppdraget ditt lister epost som kontaktinfo, burde være nummer

### ISSUE THREAD

**Issue by aslakhol** [s0lvang/Karantenehjelpen#90]
**Beskriv hva som skjer **
Kort og konsist hva som skjedde

**Annet**
Gjerne skriv hvilken device du er på og hva slags browser du bruker, og annet du tenker er nyttig,

**Comment by FredrikAugust** [comment]
Fixed by #92.
